###
#! Create a new user
POST http://localhost:3000/api/users/signup HTTP/1.1
Content-Type: application/json

{
    "username": "test-temp",
    "password": "test123",
    "confirmPassword": "test123",
    "firstName": "template",
    "lastName": "testUser",
    "email": "template.test@gmail.com"
}

###
#! Login
POST http://localhost:3000/api/users/login HTTP/1.1
Content-Type: application/json

{
    "username": "test-temp",
    "password": "test123"
}